### Get all habits
GET http://localhost:5000/api/habits

### Create a new habit
POST http://localhost:5000/api/habits
Content-Type: application/json

{
  "name": "Read for 20 minutes"
}


### Update habit completion status
PUT http://localhost:5000/api/habits/1
Content-Type: application/json

{
  "completed": true
}


### Delete a habit
DELETE http://localhost:5000/api/habits/3
